name: run

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true #fix: runner exist

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB || github.token }}
  token: ${{ secrets.TOKEN_GITHUB || github.token }}
  GH_TOKEN: ${{ secrets.TOKEN_GITHUB || github.token }}
  GITHUB_REPO: ${{github.repository}}
  WORKER_ORG: ${{ secrets.WORKER_ORG || github.repository_owner}}
  ORIGINALS: ${{github.repository_owner}}==antFame
  WORKER_TIMEOUT: ${{ github.repository_owner == 'antFame' && 15 || 360 }}

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write
  actions: write
  checks: write
  deployments: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  runner-linux:
    runs-on: ubuntu-latest
    # needs: [build]
    timeout-minutes: 250
    steps:
      - name: Free Space Before
        run: |
          echo "Free space:"
          df -h

      - name: Remove unnecessary
        run: |
          sudo rm -rf /usr/share/dotnet &
          sudo rm -rf /usr/local/lib/android &
          sudo rm -rf /opt/ghc &
          sudo rm -rf /opt/hostedtoolcache/CodeQL &
          sudo docker image prune --all --force &

      - name: Free Space
        run: |
          echo "Free space:"
          df -h

      - name: Set up Git credentials
        run: |
          git config --global user.name Nasfame
          git config --global user.email "laciferin@gmail.com"
          git config --global credential.helper '!f() { echo "username=Nasfame\npassword=$GITHUB_TOKEN"; }; f'
          git config --global push.autoSetupRemote true
          git config --global push.default matching
          git config --global alias.tags 'tag -n99'

      - uses: extractions/setup-just@v1

      - name: SSH Config
        run: |
          mkdir -p ~/.ssh/
          echo -e "Host github.com\nHostName github.com\nUser git\nIdentityFile ~/.ssh/github.com\nIdentitiesOnly yes" > ~/.ssh/config
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github.com
          chmod 600 ~/.ssh/config ~/.ssh/github.com
        shell: bash

      - uses: actions/checkout@v4
        with:
          token: ${{env.GITHUB_TOKEN}}
          submodules: false
          persist-credentials: true

      - name: Get submodules #fix: as clone submodules not working for a,b,c
        run: |
          git submodule update --init --recursive

      # - name: Write environment
      #   working-directory: ./worker
      #   run: |
      #     echo  ${{secrets.ENV}} > .env
      #     sed -i 's/ /\n/g' .env
      #     source .env

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x.x"
          check-latest: true

      - name: Boot Worker
        run: |
          just boot-worker

      # - name: Run Worker
      #   run: |
      #     just setup
      #     just worker
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.11"
      #     cache: "pip"
